repos:
  # Python代码格式化和检查
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        files: ^backend/

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^backend/
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^backend/
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # 通用检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  # 前端代码检查
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/.*\.(vue|js|ts)$
        pass_filenames: false

      - id: prettier
        name: prettier
        entry: bash -c 'cd frontend && npm run format'
        language: system
        files: ^frontend/.*\.(vue|js|ts|json|css|scss)$
        pass_filenames: false